### ISSUE TITLE
How to adjust when I didn't replicate the speedup in the paper

### ISSUE THREAD

**Issue by nienie5126** [NVIDIA/Star-Attention#3]
Hi~

Thanks for your great work and positive reply. I have some questions about inference acceleration that hoping for your guidance.

The basic information of my experiment is as follows:
**model：**Lourdle/Llama-3-8B-Instruct-Gradient-1048k
**Gpus：**8*A800 GPUS
**command：**python3 run_ruler.py \
    -n llama3_8b \
    -p  /models/Llama/Llama-3-8B-Instruct-Gradient-1048k \
    -pc llama3 \
    -a star \
    -bs 4 \ 
    -l 16384 \
    -np 8 \
    --num_samples_per_task 20
only star was changed  to ring when running baseline
**task：**niah_single
**result：**I found that the inference time for one sample was 20 seconds(context length is 16K and np is 8), while the time of ring attention was 10 seconds. 

I'm wondering if  I did something wrong and what might be the reasons for this?

**Comment by shan18** [comment]
If you see the implementation of Ring Attention in this repository:
https://github.com/NVIDIA/Star-Attention/blob/443bb9340555af7da192df7f733001f5f00382d7/model.py#L271-L274

It is actually a modified version of Ring Attention that actually uses the phase 2 from star attention for autoregressive token generation so it's not the original ring attention as proposed in [the paper](https://arxiv.org/abs/2310.01889).

In the actual ring attention implementation, the input is divided into blocks among all the ranks but when you do output generation, you only generate one token at a time and so there is no way to split it among multiple ranks.

So, in order to compare with the actual ring attention implementation, you would need to first modify the output generation in `_generate_output` function to something like:
```
outputs = self.model(
    input_ids,
    position_ids=position_ids,
    past_key_values=past_key_values,
    use_cache=True,
    num_ring_steps=-1
)
```

And then for the autoregressive generation loop, you can use the logic shown in this repo:
https://github.com/gpu-mode/ring-attention/blob/28a95e4c830f36b8a52ff21fe8f0956c7fae74c4/ring-llama/decoding.py#L58-L86

**Comment by nienie5126** [comment]
Thank you so much for your apply，I'll have a try on it.
